#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig: OS::Heat::None
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig: OS::Heat::None
  # Port assignments for the ComputeHCI
  OS::TripleO::ComputeHCI::Net::SoftwareConfig: OS::Heat::None
  # Port assignments for the ComputeLocalEphemeral
  OS::TripleO::ComputeLocalEphemeral::Net::SoftwareConfig: OS::Heat::None

parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  ControllerNetworkConfigTemplate: 'templates/single_nic_vlans/single_nic_vlans.j2'
  ComputeNetworkConfigTemplate: 'templates/single_nic_vlans/single_nic_vlans.j2'
  ComputeHCINetworkConfigTemplate: 'templates/single_nic_vlans/single_nic_vlans.j2'
  ComputeLocalEphemeralNetworkConfigTemplate: 'templates/single_nic_vlans/single_nic_vlans.j2'


  # Customize the IP subnet to match the local environment
  StorageNetCidr: '172.16.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': '172.16.1.4', 'end': '172.16.1.250'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 952


  # Customize the IP subnet to match the local environment
  StorageMgmtNetCidr: '172.16.3.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': '172.16.3.4', 'end': '172.16.3.250'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 953


  # Customize the IP subnet to match the local environment
  InternalApiNetCidr: '172.16.2.0/24'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '172.16.2.4', 'end': '172.16.2.250'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 950


  # Customize the IP subnet to match the local environment
  TenantNetCidr: '172.16.0.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '172.16.0.4', 'end': '172.16.0.250'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 951
  # MTU of the underlying physical network. Neutron uses this value to
  # calculate MTU for all virtual network components. For flat and VLAN
  # networks, neutron uses this value without modification. For overlay
  # networks such as VXLAN, neutron automatically subtracts the overlay
  # protocol overhead from this value.
  TenantNetPhysnetMtu: 1500


  # Customize the IP subnet to match the local environment
  ExternalNetCidr: '10.240.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.240.1.20', 'end': '10.240.1.250'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '10.240.1.1'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 12
  PublicVirtualFixedIPs: [{'ip_address':'10.240.1.19'}]

  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'vlan,geneve'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:4000:4001'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"
